version: '2'
services:
  web:
    image: docker.io/nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ~/code/docker/docker-fpm/nginx/conf/conf.d:/etc/nginx/conf.d
      - /var/www:/usr/share/nginx/html
  fpm:
    image: docker.io/php:fpm-alpine3.7
    volumes:
      - ~/code/docker/docker-fpm/fpm/conf:/usr/local/etc
      - /var/www/:/var/www/html
    links:
      - web
