version: '2'
services:
  nginx:
    image: docker.io/happylich/nginx
    hostname: nginx
#    networks:
#      - fn
    ports:
      - "80:80"
    volumes:
      - /usr/local/docker/docker-fpm/nginx:/etc/nginx
      - /var/www/html:/usr/share/nginx/html
  fpm:
    image: docker.io/happylich/fpm
    hostname: fpm
#    networks:
#      - fn
    volumes:
      - /usr/local/docker/docker-fpm/fpm:/usr/local/etc
      - /var/www/html:/var/www/html
#networks:
#  fn:
#    driver: bridge
